@backend_HostAddress = http://localhost:5252
@token = ""

### Inicializar usuarios de prueba (seed)
POST {{backend_HostAddress}}/api/users/seed
Content-Type: application/json

{}

### Prueba automática del endpoint /api/auth/login
POST {{backend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### Prueba automática del endpoint /api/auth/login para usuario no existente
POST {{backend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "admin2",
  "password": "admin123"
}

### Prueba automática del endpoint /api/auth/login para contraseña incorrecta
POST {{backend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin1234"
}

### Prueba automática del endpoint /api/auth/login para usuario no administrador
POST {{backend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "user123"
}

### Prueba automática del endpoint /api/users (requiere token de admin)
GET {{backend_HostAddress}}/api/users
Authorization: 
Accept: application/json
